/* TODO:  Steps to connect to the database using JDBC:
        Step1 - import package
        Step2 - load and register your driver
        Step3 - create the connection
        Step4 - create the statement
        Step5 - process the results
        Step6 - close the connection
*/

package com.utkarsh;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import static java.lang.Class.forName;
import static java.sql.DriverManager.getConnection;

public class JDBCConnection{
        public static void main(String[] args)
        {
            //Database URL, username and password initialization.
            String url = "jdbc:postgresql://localhost:5432/demo";
            String username = "postgres";
            String password = "Cybertron@123";
            String sql = "select * from student where sid = 5";
            try{
                //Step1 - import package - Done in the import statement above

                //Step2 - Load and register your driver : this can be let aside because in higher versions of JDBC, the driver is automatically loaded
                //Class.forName("org.postgresql.Driver");

                //Step3 - Create the Connection
                Connection con = DriverManager.getConnection(url, username, password);
                System.out.println("Connection established successfully!");

                //Step4 - Create the statement : This is not needed for just establishing a connection, but is used when you want to execute SQL queries.
                Statement st = con.createStatement();

                //Step5 - Process the results : This is also not needed for just establishing a connection, but is used when you want to execute SQL queries.
                ResultSet rs = st.executeQuery(sql); // ResultSet is a table of data representing a database result set, which is usually generated by executing a statement that queries the database.
                System.out.println(rs.next()); // Move the cursor to the next row of the ResultSet if it is going to the next row it means that the query has returned some results.

                //Step6 -  Close the connection
                con.close();
                System.out.println("Connection closed successfully!");

            }
            catch(Exception e){
                e.printStackTrace();
            }

        }
}